language: node_js
node_js: '8'

git:
  depth: 3

branches:
  only:
    - master
    - /^greenkeeper/.*$/

services:
  - mongodb

env:
  global:
    - NODE_ENV=test
    - PORT=3000
    - JWT_SECRET=bA2xcjpf8y5aSUFsNB2qN5yymUBSs6es3qHoFpGkec75RCeBb8cpKauGefw5qy4
    - JWT_EXPIRATION_MINUTES=15
    - MONGO_URI=mongodb://travis:test@localhost:27017/express-es8-rest-boilerplate
    - MONGO_URI_TESTS=mongodb://travis:test@localhost:27017/express-es8-rest-boilerplate
    - RATE_LIMIT_TIME=1
    - RATE_LIMIT_REQUEST=2000

script: yarn validate

before_install: yarn global add greenkeeper-lockfile@1
before_script:
  - greenkeeper-lockfile-update
  - sleep 10
  - mongo express-es8-rest-boilerplate --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
after_script: greenkeeper-lockfile-upload

# deploy:
# - provider: script
#   script: yarn deploy

after_success: yarn coverage
